[package]
name = "noi-alias"
version = "0.1.0"
authors = ["frostornge <frostornge@gmail.com>"]
edition = "2018"

[dependencies]
cosmwasm-std = "1.0.0"

osmo-bindings = { git="https://github.com/osmosis-labs/bindings", rev="9b9278f" }
